### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by Xbygone** [Gktwo/minty-mog#1]
game is crashing when i summoning or entering the story missions

**Comment by Gktwo** [comment]
Only Taiwan server version, or download the latest action build

**Comment by Gktwo** [comment]
I have not added version check function yet. If it‘s crashing, please wait for the update

**Comment by Xbygone** [comment]
> Only Taiwan server version, or download the latest action build

im using global server. i hope u will for it

**Comment by Gktwo** [comment]
gktwo#4158  You can add my Discord friend, I need some global version files to upgrade

**Comment by Xbygone** [comment]
stbygone i added you

**Comment by Gktwo** [comment]
Already supports global servers
